name: f_limit
description: A Dart concurrency limiter for async operations with advanced features.
version: 2.0.0
homepage: https://github.com/fluttercandies/f_limit
repository: https://github.com/fluttercandies/f_limit
issue_tracker: https://github.com/fluttercandies/f_limit/issues
topics:
  - isolate
  - future-queue
  - concurrency
  - queue
  - task-queue

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
